apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: ves-system
spec:
  type: LoadBalancer
  ports:
  - name: ike
    port: 4500
    protocol: UDP
    targetPort: 4500
  selector:
    app: ver
  sessionAffinity: None
